language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "nightly"
install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: cpetrich
  password:
  distributions: "sdist bdist_wheel"
  on:
    tags: true
