language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- nightly
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: cpetrich
  password:
    secure: "kB+pARQf/9bX2Tm4kTNVTBXZsOlN5U76QWS7Mxlo7c+rXByFxxjln6kC8zzWE5a+cLKf1Fh5H1Un1pPgxaNL5UcJbGPZGgqWRtu56NMRz0cAed44t+tOAyaOPr3uhUElEAgDO6EMUblijNWt3f8Ufjish2SldotagHRm1J71FDqxcty7lqf82II25Th1RaLgxoBzANj8nRB+L4Sw66JB3ng9XA/dtVRxWvQm/JBXmQlTGScwtUp7OMdbQHSSLU8Zulmj35ZJe+SGKq06s8usBJWl9WDBbcAyaInohmQWptxprFiEbEsRKWEXO++IuvAHKu+NUJLaFADF2MN3HDtZaqw/ZmwFFLy7Myet4zJqqX2Qpk74XOvAbJZKQZFi3Do3swDuEzSYhk3z2PqKGktDZfiyFy5pkUO0jt+fjxMaz+Tm1RgwSJGgvj15Ef9Xlb69BubDkSAGdO7mRSGP6QVSKxGAYGyVJfLxCDDgslaN/QChuL7fbQviOUPCH9mA/S/7jWHU/Tx9z2qXpjwaQa2AAZdtLPQh+csmov6eX2xk9HiB+QJMCyna7fe2WPLx3u9uluvVbT1NcEifo3rD8+eAXJ74MwwE2LOgTzfeLfB1XyCVqYlFDJIePHYEsWga0xVmyKZdB2tg2H+pu6l5zYB0O95HbSMWkJUOP7deNgcPpXo="
  distributions: "sdist bdist_wheel"
  on:
    condition: $TRAVIS_PYTHON_VERSION == "3.6"
    branch: master
    tags: true

  provider: pypi
  server: https://test.pypi.org/legacy/
  user: cpetrich
  password:
    secure: "kB+pARQf/9bX2Tm4kTNVTBXZsOlN5U76QWS7Mxlo7c+rXByFxxjln6kC8zzWE5a+cLKf1Fh5H1Un1pPgxaNL5UcJbGPZGgqWRtu56NMRz0cAed44t+tOAyaOPr3uhUElEAgDO6EMUblijNWt3f8Ufjish2SldotagHRm1J71FDqxcty7lqf82II25Th1RaLgxoBzANj8nRB+L4Sw66JB3ng9XA/dtVRxWvQm/JBXmQlTGScwtUp7OMdbQHSSLU8Zulmj35ZJe+SGKq06s8usBJWl9WDBbcAyaInohmQWptxprFiEbEsRKWEXO++IuvAHKu+NUJLaFADF2MN3HDtZaqw/ZmwFFLy7Myet4zJqqX2Qpk74XOvAbJZKQZFi3Do3swDuEzSYhk3z2PqKGktDZfiyFy5pkUO0jt+fjxMaz+Tm1RgwSJGgvj15Ef9Xlb69BubDkSAGdO7mRSGP6QVSKxGAYGyVJfLxCDDgslaN/QChuL7fbQviOUPCH9mA/S/7jWHU/Tx9z2qXpjwaQa2AAZdtLPQh+csmov6eX2xk9HiB+QJMCyna7fe2WPLx3u9uluvVbT1NcEifo3rD8+eAXJ74MwwE2LOgTzfeLfB1XyCVqYlFDJIePHYEsWga0xVmyKZdB2tg2H+pu6l5zYB0O95HbSMWkJUOP7deNgcPpXo="
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION == "3.6"
