language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- nightly

install:
- pip install tox-travis
- pip install twine
- python setup.py install

script: tox

after_success:
- test "${TRAVIS_PYTHON_VERSION}" == "3.6" && test "${TRAVIS_TAG}" == "" && test "${TRAVIS_PULL_REQUEST}" == "false" && python setup.py sdist && python setup.py bdist_wheel --universal && twine upload -u cpetrich -p ${TEST_PASSWORD} --repository https://test.pypi.org/legacy/ --repository-url https://test.pypi.org/legacy/  dist/*.*
- test "${TRAVIS_PYTHON_VERSION}" == "3.6" && test "${TRAVIS_TAG}" != "" && test "${TRAVIS_PULL_REQUEST}" == "false" && python setup.py sdist && python setup.py bdist_wheel --universal && twine upload -u cpetrich -p ${PYPI_PASSWORD} --repository https://upload.pypi.org/legacy/ --repository-url https://upload.pypi.org/legacy/  dist/*.*
