language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- nightly
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: cpetrich
  password:
    secure: tG2dYkEdhtNoQ9NwdNqPeOupJbt1/GQqidS5HVgI0w6Qj3QB3X1SUW+V3NiNg/aIrwm1/lW02oQa9lZP4LFIc3A5yi4Hd8lzSwuO+2UaT52XUApp8/Qn79s81Ls0RFDoxMp3ih6NHgOt8dhwI4rHXrl5NO+5J9hZJtsMgtb64mpaAUFJ+VDXmCVt+CYn8U3Wwe1jRnlC4K4MzKjmW5gO+XtLFx6o6JBkI1sD29TkxC2d/f4ooHbY71cnbkeVIG+EuuiKSW6K3/x8os4SJhfcw3hsAFZbYOALwj6b7vl5vWuT8PBd3Y7w4rFsWfNdcxCCwfy7IBrWaHQxxDjsUqV5IH7K+uy0Xotb46lFUS4vzpUTUYI8EEVOT0YjXujFfLA9mMmuooNtQZpjdrFgbTamN6RjS8kp2X+NopVl3tTg1C8lN2u+/kXYrac3iQcNKQKQj3dMgJFAQG82DQoiYfergf0pzN3ScEoIbNXCN81VR/NujST8V00OeevX3Wohl4Ax5vi6MjpKcz7xJMirT2yB9lc00Tq94gBPHruO77HT9bEmltbj2HPANP4DTiZ8oZbkr/zIBXKNLZzzmPsscqQQ2dMm9pIeuGQIV66zBZD3Hy8hrjJt1613QB6H5utN/S7T5itON7U9tLuAaXc+KxJO2CilGB3Oei3vBKCohhzVc/c=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == "3.4"

  provider: pypi
  server: https://test.pypi.org/legacy/
  user: cpetrich
  password:
    secure: tG2dYkEdhtNoQ9NwdNqPeOupJbt1/GQqidS5HVgI0w6Qj3QB3X1SUW+V3NiNg/aIrwm1/lW02oQa9lZP4LFIc3A5yi4Hd8lzSwuO+2UaT52XUApp8/Qn79s81Ls0RFDoxMp3ih6NHgOt8dhwI4rHXrl5NO+5J9hZJtsMgtb64mpaAUFJ+VDXmCVt+CYn8U3Wwe1jRnlC4K4MzKjmW5gO+XtLFx6o6JBkI1sD29TkxC2d/f4ooHbY71cnbkeVIG+EuuiKSW6K3/x8os4SJhfcw3hsAFZbYOALwj6b7vl5vWuT8PBd3Y7w4rFsWfNdcxCCwfy7IBrWaHQxxDjsUqV5IH7K+uy0Xotb46lFUS4vzpUTUYI8EEVOT0YjXujFfLA9mMmuooNtQZpjdrFgbTamN6RjS8kp2X+NopVl3tTg1C8lN2u+/kXYrac3iQcNKQKQj3dMgJFAQG82DQoiYfergf0pzN3ScEoIbNXCN81VR/NujST8V00OeevX3Wohl4Ax5vi6MjpKcz7xJMirT2yB9lc00Tq94gBPHruO77HT9bEmltbj2HPANP4DTiZ8oZbkr/zIBXKNLZzzmPsscqQQ2dMm9pIeuGQIV66zBZD3Hy8hrjJt1613QB6H5utN/S7T5itON7U9tLuAaXc+KxJO2CilGB3Oei3vBKCohhzVc/c=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION == "3.4"
